### ISSUE TITLE
Error setting up the system

### ISSUE THREAD

**Issue by geekyJock8** [iiitv/Odyssy#64]
## ModuleNotFoundError: No module named 'views'

Every instruction is successfully executed till "_$ python manage.py migrate_". When I run this command I get following list of errors: 
```python
Traceback (most recent call last):                                                                                                    
  File "manage.py", line 11, in <module>                                                                                              
    execute_from_command_line(sys.argv)                                                                                               
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line                  
    utility.execute()                                                                                                                 
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute                                    
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python3.6/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3.6/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/geeky_jock/Downloads/Odyssy/wsgi/odyssy/odyssy/urls.py", line 35, in <module>
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  File "/usr/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/geeky_jock/Downloads/Odyssy/wsgi/odyssy/events/urls.py", line 3, in <module>
    import views
ModuleNotFoundError: No module named 'views'
```

**Comment by mohitkyadav** [comment]
@geekyJock8 it seems you are trying to run `odyssy` with Python 3.5 or +. 
Here's a fix, change line 11 to `from . import views`.

**Comment by singhpratyush** [comment]
@mohitkyadav: Recommending change of source locally is not a good practice.
@geekyJock8: Please run it with `python2.7`. It is generally called `python2` or `python2.7` depending on the OS. If you are still having trouble, please let us know about your OS.

**Comment by mohitkyadav** [comment]
@singhpratyush sir, got that, but when I run the project with Python2.7 interpreter it still shows error I am using PyCharm on windows and .

**Comment by geekyJock8** [comment]
@singhpratyush  When I use python2 or python2.7, I get
`Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
`

I'm using **_Manjaro Linux_**. It's an Arch Linux based OS.

**Comment by yashLadha** [comment]
Try to upgarde the django-version, or execute `pip install -r requirements.txt` for installing necessary dependencies.

**Comment by geekyJock8** [comment]
@yashLadha As I mentioned earlier I've executed all the previous commands and all of them executed successfully. Here are further details:
```
Requirement already satisfied: django==1.10 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: psycopg2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: django-photologue in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: django-taggit in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: ExifRead>=2.1.2 in /usr/lib/python3.6/site-packages (from django-photologue->-r requirements.txt (line 3))                                                                                                                                   
Requirement already satisfied: Pillow>=2.7.0 in /usr/lib/python3.6/site-packages (from django-photologue->-r requirements.txt (line 3))                                                                                                                                     
Requirement already satisfied: django-sortedm2m>=1.3.3 in /usr/lib/python3.6/site-packages (from django-photologue->-r requirements.txt (line 3))                                                                                                                           
Requirement already satisfied: olefile in /usr/lib/python3.6/site-packages (from Pillow>=2.7.0->django-photologue->-r requirements.txt (line 3))
```

**Comment by mohitkyadav** [comment]
@geeckyJock I think you are installing django in `python 3.6` ` /usr/lib/python3.6/site-packages`.
Please run all commands with `python2.7`. `Requirement already satisfied: django==1.10 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1))` notice python version in this line, it's 3.6 not 2.7.

**Comment by singhpratyush** [comment]
@geekyJock8: Similar to `python2` and `python2.7`, you would also be having `pip2` or `pip2.7`. Use that to install the packages - 
```sh
$ sudo -H pip2 install -r requirements.txt
```

**Comment by geekyJock8** [comment]
@singhpratyush It says
` sudo: pip2: command not found`
and 
`sudo: pip2.7: command not found`

**Comment by singhpratyush** [comment]
Then you'll need to install `python2` compatible `pip` from your package manager (`python2-pip` I guess).

**Comment by geekyJock8** [comment]
@singhpratyush Thanks, Installing python2-pip did the trick for me.
